export const chats = [
  {
    chatName: "John 200L MBBS",
    msgSent: [],
    msgRecieved: ["alright thank you very much"],
    timeOfLastChat: "17:00",
    seen: false,
  },
  {
    chatName: "Eniola 2",
    msgSent: [],
    msgRecieved: ["That's a good idea. Will do"],
    timeOfLastChat: "16:50",
    seen: false,
  },
  {
    chatName: "Mercy",
    msgSent: [],
    msgRecieved: ["Okay Okay 😂"],
    timeOfLastChat: "16:50",
    seen: true,
  },
  {
    chatName: "Shaydee Coder",
    msgSent: ["Alright, thanks"],
    msgRecieved: [],
    timeOfLastChat: "11:07",
    seen: false,
  },
  {
    chatName: "Ojonimi",
    msgSent: ["Alright, thanks"],
    msgRecieved: [],
    timeOfLastChat: "10:34",
    seen: true,
  },
  {
    chatName: "Josiah Frank",
    msgSent: [],
    msgRecieved: ["Yh"],
    timeOfLastChat: "Yesterday",
    seen: true,
  },
  {
    chatName: "Sis",
    msgSent: ["Alright, thanks"],
    msgRecieved: [],
    timeOfLastChat: "Yesterday",
    seen: true,
  },
  {
    chatName: "Unana",
    msgSent: [],
    msgRecieved: ["Yeah"],
    timeOfLastChat: "Monday",
    seen: false,
  },
  {
    chatName: "Francis S",
    msgSent: [],
    msgRecieved: ["Thanks bro 😭 😭"],
    timeOfLastChat: "Monday",
    seen: false,
  },
  {
    chatName: "Adedapo 200L MBBS",
    msgSent: [],
    msgRecieved: ["Alright then 👌"],
    timeOfLastChat: "Monday",
    seen: false,
  },
  {
    chatName: "Emmanuella",
    msgSent: ["Hey"],
    msgRecieved: [],
    timeOfLastChat: "Sunday",
    seen: false,
  },
];
