export let chats = [
  {
    chatName: "Stephanie🌹",
    msgSent: [],
    msgRecieved: ["Heyy"],
    chatTime: [
      {
        dayOfMessage: "2025-10-10",
        timeOfLastChatHour: 17,
        timeOfLastChatMins: 0,
        timeOfLastChatSec: 16,
      },
    ],
    seen: false,
    id: 0,
    unread: true,
  },
  {
    chatName: "Eniola 2",
    msgSent: [],
    msgRecieved: ["That's a good idea. Will do"],
    chatTime: [
      {
        dayOfMessage: "2025-10-10",
        timeOfLastChatHour: 16,
        timeOfLastChatMins: 50,
        timeOfLastChatSec: 22,
      },
    ],
    seen: false,
    id: 1,
    unread: true,
  },
  {
    chatName: "Mercy",
    msgSent: [],
    msgRecieved: ["Okay Okay 😂"],
    chatTime: [
      {
        dayOfMessage: "2025-10-10",
        timeOfLastChatHour: 15,
        timeOfLastChatMins: 30,
        timeOfLastChatSec: 39,
      },
    ],
    seen: true,
    id: 2,
    unread: false,
  },
  {
    chatName: "Shaydee Coder",
    msgSent: ["Alright, thanks"],
    msgRecieved: [],
    chatTime: [
      {
        dayOfMessage: "2025-10-10",
        timeOfLastChatHour: 11,
        timeOfLastChatMins: 7,
        timeOfLastChatSec: 42,
      },
    ],
    seen: false,
    id: 3,
    unread: false,
  },
  {
    chatName: "Japheth",
    msgSent: ["Brooo"],
    msgRecieved: [],
    chatTime: [
      {
        dayOfMessage: "2025-10-10",
        timeOfLastChatHour: 10,
        timeOfLastChatMins: 34,
        timeOfLastChatSec: 25,
      },
    ],
    seen: true,
    id: 4,
    unread: false,
  },
  {
    chatName: "Josiah Frank",
    msgSent: [],
    msgRecieved: ["Yh"],
    chatTime: [
      {
        dayOfMessage: "2025-10-10",
        timeOfLastChatHour: 9,
        timeOfLastChatMins: 20,
        timeOfLastChatSec: 19,
      },
    ],
    seen: true,
    id: 5,
    unread: false,
  },
  {
    chatName: "Sis",
    msgSent: ["Alright, no problem"],
    msgRecieved: [],
    chatTime: [
      {
        dayOfMessage: "2025-10-10",
        timeOfLastChatHour: 8,
        timeOfLastChatMins: 50,
        timeOfLastChatSec: 12,
      },
    ],
    seen: true,
    id: 6,
    unread: false,
  },
  {
    chatName: "Unana",
    msgSent: [],
    msgRecieved: ["Yeah"],
    chatTime: [
      {
        dayOfMessage: "2025-10-10",
        timeOfLastChatHour: 8,
        timeOfLastChatMins: 32,
        timeOfLastChatSec: 25,
      },
    ],
    seen: false,
    id: 7,
    unread: true,
  },
  {
    chatName: "Micheal",
    msgSent: [],
    msgRecieved: ["Hwfr na"],
    chatTime: [
      {
        dayOfMessage: "2025-10-09",
        timeOfLastChatHour: 8,
        timeOfLastChatMins: 0,
        timeOfLastChatSec: 29,
      },
    ],
    seen: false,
    id: 8,
    unread: true,
  },
  {
    chatName: "Joshua",
    msgSent: [],
    msgRecieved: ["Alright then 👌"],
    chatTime: [
      {
        dayOfMessage: "2025-10-09",
        timeOfLastChatHour: 7,
        timeOfLastChatMins: 20,
        timeOfLastChatSec: 17,
      },
    ],
    seen: false,
    id: 9,
    unread: true,
  },
  {
    chatName: "Emmanuella",
    msgSent: ["Hey"],
    msgRecieved: [],
    chatTime: [
      {
        dayOfMessage: "2025-10-09",
        timeOfLastChatHour: 4,
        timeOfLastChatMins: 45,
        timeOfLastChatSec: 21,
      },
    ],
    seen: false,
    id: 10,
    unread: false,
  },
  {
    chatName: "Bivins",
    msgSent: ["Hwfr bro"],
    msgRecieved: [],
    chatTime: [
      {
        dayOfMessage: "2025-10-09",
        timeOfLastChatHour: 2,
        timeOfLastChatMins: 45,
        timeOfLastChatSec: 18,
      },
    ],
    seen: true,
    id: 11,
    unread: false,
  },
  {
    chatName: "Churchill",
    msgSent: ["What's good Churchill"],
    msgRecieved: [],
    chatTime: [
      {
        dayOfMessage: "2025-10-06",
        timeOfLastChatHour: 2,
        timeOfLastChatMins: 30,
        timeOfLastChatSec: 16,
      },
    ],
    seen: false,
    id: 12,
    unread: false,
  },
  {
    chatName: "Princewill",
    msgSent: [],
    msgRecieved: ["Guy u sabi😂😂"],
    chatTime: [
      {
        dayOfMessage: "2025-10-06",
        timeOfLastChatHour: 2,
        timeOfLastChatMins: 20,
        timeOfLastChatSec: 23,
      },
    ],
    seen: false,
    id: 13,
    unread: true,
  },
  {
    chatName: "Timayin",
    msgSent: ["Ohh, I didn’t hear well😅"],
    msgRecieved: [],
    chatTime: [
      {
        dayOfMessage: "2025-10-06",
        timeOfLastChatHour: 2,
        timeOfLastChatMins: 0,
        timeOfLastChatSec: 16,
      },
    ],
    seen: false,
    id: 14,
    unread: false,
  },
  {
    chatName: "Bem",
    msgSent: [],
    msgRecieved: ["I'm trying to build something"],
    chatTime: [
      {
        dayOfMessage: "2025-10-05",
        timeOfLastChatHour: 1,
        timeOfLastChatMins: 0,
        timeOfLastChatSec: 24,
      },
    ],
    seen: false,
    id: 15,
    unread: true,
  },
];
